apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  # this is an L4 Load Balancer
  type: NodePort
  ports:
    - port: {{ .Values.shortener.servicePort | default 5000 }} # what port is our service going to expose?
      targetPort: {{ .Values.shortener.containerPort | default 5000 }} # what port are our containers listening on?
  selector:
    app: auth-service-app
