apiVersion: v1
kind: Secret # we use secret to store our service mongo-db-user and mongo-db-pass configurations which is more safer than ConfigMap.
metadata:
  name: auth-database-credentials
  # we allow the user to specify a namespace
  namespace: "{{ .Values.namespace | default "default" }}"
# we set the secret to use base64 encoding for values as
# a reminder that this is confidential data
type: Opaque
# we set the mongo admin root credentials set by the user,
# this allows for consistent access to the persisted database
# after restarts
data:
  mongo-db-user: {{ .Values.auth.database.user | b64enc }}
  mongo-db-pass: {{ .Values.auth.database.pass | b64enc }}
---
apiVersion: v1
kind: ConfigMap # we define configuration map to store mongo-db-name 
metadata:
  name: auth-database-configmap
# we leave the name of the database in a plain configmap
# as it does not represent critical information
data:
  mongo-db-name: {{ .Values.auth.database.name }}