apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: "{{ .Values.namespace | default "default" }}"
type: Opaque
data:
  # generate a 4096 RSA key
  rsa-privatekey: {{ genPrivateKey "rsa" | b64enc | quote }}
  # sets the user provided password salt, or it generates a random 32 chars string
  password-salt: {{ .Values.auth.passwordSalt | default (randAscii 32 | b64enc | quote) }}
