apiVersion: v1
kind: Service
metadata:
  name: auth-database
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.database.port }}
      targetPort: {{ .Values.auth.database.port }}
  selector:
    app: auth-database-app
