apiVersion: v1
kind: Secret
metadata:
  name: auth-database-credentials
  namespace: "{{ .Values.namespace | default "default" }}"
type: Opaque
data:
  mongo-db-user: {{ .Values.auth.database.user }}
  mongo-db-pass: {{ .Values.auth.database.pass }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-database-configmap
data:
  mongo-db-name: {{ .Values.auth.database.name }}