apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 
  selector:
    app: front-service-app
