apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: LoadBalancer
  selector:
    app: front-service-app
  ports:
    - protocol: TCP
      port: 80
