apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service-deployment
  namespace: "{{ .Values.namespace | default "default" }}"
  labels:
    kubernetes.io/name: front-service-deployment
    kubernetes.io/component: frontend
    app: front-service-app
spec:
  replicas: {{ .Values.front.replicas | default 3 }}
  selector:
    matchLabels:
      app: front-service-app
  template:
    metadata:
      labels:
        app: front-service-app
    spec:
      containers:
        - name: front-service-container
          image: "docker.io/marinoandrea/wscbs-front-service:{{ .Values.front.imageVersion | default "latest" }}"
          ports:
            - containerPort: 80
