apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: url-shortener-ingress-class
  # we allow the user to specify a namespace
  namespace: "{{ .Values.namespace | default "default" }}"
  annotations:
    # redundant setting to ensure that this class will be used even if the 
    # user goes for the default (not possible unless the chart is modified)
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  # we want nginx as we like the url rewrite rule (see ingreess.yaml)
  controller: k8s.io/ingress-nginx
