apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-database-credentials
  namespace: "{{ .Values.namespace | default "default" }}"
type: Opaque
data:
  mongo-db-user: {{ .Values.shortener.database.user | b64enc }}
  mongo-db-pass: {{ .Values.shortener.database.pass | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-database-configmap
data:
  mongo-db-name: {{ .Values.shortener.database.name }}