kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: url-shortener-policy-deny-all-db
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  podSelector:
    matchLabels:
      app: url-shortener-database-app
  policyTypes:
    - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: url-shortener-policy-allow-db-from-api
spec:
  podSelector:
    matchLabels:
      app: url-shortener-database-app
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: url-shortener-app
      ports:
        - protocol: TCP
          port: {{ .Values.shortener.database.port }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: url-shortener-policy-allow-db-to-api
spec:
  podSelector:
    matchLabels:
      app: url-shortener-database-app
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: url-shortener-app
      ports:
        - protocol: TCP
          port: {{ .Values.shortener.database.port }}