apiVersion: v1
kind: Service
metadata:
  name: url-shortener-database
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.shortener.database.port }}
      targetPort: 27017
  selector:
    app: url-shortener-database-app
