apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-shortener-database-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 250Mi
