apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  namespace: "{{ .Values.namespace | default "default" }}"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.shortener.servicePort | default 5000 }} # what port is our service going to expose?
      targetPort: {{ .Values.shortener.containerPort | default 5000 }} # what port are our containers listening on?
  selector:
    app: url-shortener-app # which pods should be targeted by this service?
