version: "3.8"

services:
  auth:
    build:
      context: services/auth-service
    ports:
      - "5001:5000"
    environment:
      - RSA_PRIVATE_PATH=${RSA_PRIVATE_PATH}
      - RSA_PUBLIC_PATH=${RSA_PUBLIC_PATH}
      - PASSWORD_SALT=${PASSWORD_SALT}

  shortener:
    build:
      context: services/url-shortener
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth:5000
    depends_on:
      - auth