apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: url-shortener-deployment 
  labels: 
    app: url-shortener-app 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: url-shortener 
  template: 
    metadata: 
      labels: 
        app: url-shortener
    spec: 
      containers: 
      - name: url-shortener-container 
        image: wangjycode/wscbs-project_short:v1 
        ports: 
        - containerPort: 5000 
