# syntax=docker/dockerfile:1

FROM python:3.9-slim

ENV APP_DIR /usr/local/src/url-shortener

COPY . ${APP_DIR}/

WORKDIR ${APP_DIR}

RUN apt-get update && apt-get install -y pipenv

RUN pipenv install --system --deploy && pip install gunicorn

EXPOSE 5000

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--reload", "app:app" ]