# using python:3.9-slim, this is the first stage image also used as a runtime environment.
# This version is based on Alpine Linux, which is a minimal and lightweight distribution.
FROM python:3.9-slim

# this path represents the root directory for our python application inside the container
ENV APP_DIR /usr/local/src/url-shortener

# in development, we copy the entire directory as we
# need local development files (such as the RSA keys)
COPY . ${APP_DIR}/

# we set an appropriate work directory to highlight this is
# just a temporary folder and that this container should not be used as
# the runtime environment
WORKDIR ${APP_DIR}

# update apt repository and install pipenv for compile 
RUN apt-get update && apt-get install -y pipenv

# we use pipenv to install the dependences of the service and install gunicorn.
RUN pipenv install --system --deploy && pip install gunicorn

# we expose 5000 as the service port
EXPOSE 5000

# we use this command to run the application
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--reload", "app:app" ]