apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          image: marinoandrea/wscbs-auth-service:1.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: auth-rsa-keys-volume
              readOnly: true
              mountPath: "/etc/rsa"
          resources:
            limits:
              cpu: 1
              memory: 1G
          env:
            - name: RSA_PUBLIC_PATH
              value: "/etc/rsa/rsa-publickey"
            - name: RSA_PRIVATE_PATH
              value: "/etc/rsa/rsa-privatekey"
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: auth-password-salt
                  key: password-salt
      volumes:
        - name: auth-rsa-keys-volume
          secret:
            secretName: auth-rsa-keys
